fix: refactor producer/consumer design
nikomatsakis/github-metrics pull request #25
Opened 2021-06-16 22:18 UTC by chazkiker2

# Description

- closes #24 
- re-structure the producer/consumer split into its own mod

2021-06-16 22:46 UTC, chazkiker2 commented on src/metrics.rs
> +    fn spawn_producer_task(&self, tx: Sender<Vec<String>>) {
this code does not compile due to the errors described in [this Zulip message](https://github-metrics.zulipchat.com/#narrow/stream/291433-general/topic/generalize.20producer.2Fconsumer/near/242951396)

Comments for error are included in code currently.

2021-06-17 01:10 UTC, nikomatsakis requested changes

2021-06-17 01:10 UTC, nikomatsakis approved these changes

2021-06-17 01:10 UTC, nikomatsakis commented
Actually I changed my mind. Let's manage that in a follow-up PR.

2021-06-17 01:10 UTC, merged